natalies_second_chance_project/dogs/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static #allows django to serve up media files
from django.conf import settings

app_name = 'dogs'

urlpatterns = [
    path('', views.DogListView.as_view(), name='list'),
    path('<int:pk>/', views.DogDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', views.DogDeleteView.as_view(), name='delete'),
    path('create/', views.DogCreateView.as_view(), name='create' ),
    path('update/<int:pk>', views.DogUpdateView.as_view(), name='update'),
    
]

natalies_second_chance_project/natalies_second_chance/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.urls import path, include
from django.contrib.auth.views import LogoutView

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('contact/', views.ContactPageView.as_view(template_name='contact.html'), name='contact'),
    path('dogs/', include('dogs.urls')),
    path('events/', views.TemplateView.as_view(template_name='events.html'), name='events'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('test_login/', views.test_user_login, name='test_login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

natalies_second_chance_project/dogs/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Dog(models.Model):
    # Size choices
    SMALL = "SM"
    MEDIUM = "MD"
    LARGE = "LG"
    EXTRA_LARGE = "XL"
    DOG_SIZE_CHOICES = (
        (SMALL, "Small (Under 10 lbs)" ),
        (MEDIUM, "Medium (10 to 40 lbs)" ),
        (LARGE, "Large (40 to 100 lbs)" ),
        (EXTRA_LARGE, "X-Large (Over 100 lbs)" ),
    )

    #Sex Choices
    MALE = 'M'
    FEMALE = 'F'
    DOG_SEX_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    name = models.CharField(max_length=50)
    breed = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    description = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='dog_images/', default="default_dog.png")
    size = models.CharField(max_length=2, choices=DOG_SIZE_CHOICES)
    sex = models.CharField(max_length=1, choices=DOG_SEX_CHOICES )

    def get_absolute_url(self):
        return reverse('dogs:detail', kwargs={'pk': self.pk})
    
    class Meta:
        verbose_name = ('Dog')
        verbose_name_plural = ('Dogs')
        ordering = ('-pk',)
    
    def __str__(self):
        return self.name

natalies_second_chance_project/dogs/forms.py
from django import forms
from django.core import validators
from django.utils.safestring import mark_safe
from django.forms.widgets import ClearableFileInput
from .models import Dog

class ImageClearableFileInput(ClearableFileInput):
    #remove the label 'Change' from the image button as it will be hidden with CSS
    input_text = ''

class DogCreateForm(forms.ModelForm):
    name = forms.CharField()
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":7}))
    image = forms.ImageField(
        label=mark_safe('<i class="fas fa-download"></i> Choose Image...'),
        widget=ImageClearableFileInput,
        required=False
    )

    class Meta:
        model = Dog
        fields = ['name', 'breed', 'age', 'size', 'sex', 'description', 'image' ]

natalies_second_chance_project/dogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from .models import Dog
from .forms import DogCreateForm


class DogCreateView(LoginRequiredMixin, CreateView):
    model = Dog
    form_class = DogCreateForm


class DogListView(ListView):
    model = Dog
    template_name = "dogs/dog_list.html"
    context_object_name = 'dogs'
    paginate_by = 10


class DogDetailView(DetailView):
    form_class = DogCreateForm
    model = Dog
    template_name = 'dogs/dog_detail.html'


class DogUpdateView(LoginRequiredMixin, UpdateView):
    model = Dog
    form_class = DogCreateForm
    template_name = "dogs/dog_form.html"


class DogDeleteView(LoginRequiredMixin, DeleteView):
    model = Dog
    success_url = reverse_lazy('dogs:list')
    context_object_name = 'dog'

natalies_second_chance_project/natalies_second_chance/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic.base import TemplateView

from dogs.models import Dog

#Set Api Key for handling payments
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY



class HomePageView(TemplateView):
    template_name = 'index.html'

    def post(self, request, **kwargs):
        context = self.get_context_data()
        post_data = self.request.POST
        token = self.request.POST.get('stripeToken', '')
        
        # Check for custom donation
        if post_data.get('custom-donation-option'):
            amount = float(post_data.get('custom-donation-option')
                           ) * 100  # convert donation to cents
        else:
            # Defaults to $5.00 if the donation amount never changed
            amount = post_data.get('donation-option', 500)

        try:
            # Create the stripe charge
            charge = stripe.Charge.create(
                amount=int(amount),  # convert to integer of cents in USD
                currency='usd',
                description='Donation',
                source=token
            )
            context["amount"] = int(amount) / 100  # back to float for context
            context["payment"] = 'success'
            context["payment_header"] = 'Success!'
            context["payment_message"] = "Congratulate yourself on being awesome!<br>We appreciate your generosity."

        except stripe.error.CardError:
            context["payment"] = 'declined'
            context["payment_header"] = 'Payment Method Declined.'
            context["payment_message"] = "There was an error in processing your card"

        except stripe.error.InvalidRequestError:
            """
            If a user refreshes the page after payment confirmation the stripeToken
            will be invalid and give an Invalid Request Error, this handles that exception
            gracefully without causing any issue for the user
            """
            pass

        # Any general errors not on stripe's end
        except:
            context["payment"] = 'error'
            context["payment_header"] = 'Error.'
            context["payment_message"] = "There was an error in processing your donation."

        return render(request, 'index.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        context['dogs'] = Dog.objects.all().order_by('-pk')[:6]
        return context


class EventPageView(TemplateView):
    template_name = 'events.html'


class ContactPageView(TemplateView):
    template_name = 'contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['maps_key'] = settings.GOOGLE_MAPS_KEY
        return context

def test_user_login(request):
    """ Allows anonymous user login to demo site
    NOT TO BE USED IN PRODUCTION
    """
    user = authenticate(request, username='test', password='test1234!')
    if user is not None:
        #login the test user (pre-made in the admin)
        login(request, user)
        messages.success(request, 'Logged in as Test User')
    else:
        messages.error(request, 'Could not successfully log in')
    return redirect(reverse('home'))

natalies_second_chance_project/dogs/templates/dogs/dog_confirm_delete.html
{% extends "dogs/dog_detail.html" %}

{% block story %}
<form method="post">
    {% csrf_token %}
    <div class="text-center">
        <p class="text-lg">Are you sure you want to delete "{{ dog }}"?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
        <a href="{% url 'dogs:detail' pk=dog.pk %}" class="btn btn-secondary text-dark">Cancel</a>
    </div>
</form>
{% endblock story %}

natalies_second_chance_project/dogs/templates/dogs/dog_detail.html
{% extends "base.html" %} 
{% load static %} 
{% block title %} {{ dog.name }} {% endblock %} 
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/dog_detail.min.css' %}" type="text/css">

{% endblock %}

{% block navigation %}
{% include "includes/detail_navbar.html" %}
{% endblock navigation %}

{% block page_header %}
<div class="page-header header-filter"> 
<div class="container pb-0 mb-0">
    <div class="row align-items-center justify-content-right">
        <div class="col-md-6 left">
            <div class="card">
                <div class="text-center d-flex align-items-center justify-content-center card-header card-header-{%if dog.sex == 'M'%}info{% else %}rose{%endif%}">
                    <h1 class="title my-0 text-center d-inline" id="title">
                        {{ dog.name }}              
                    </h1>
                </div>
                <div class="container my-2">
                    <img  class="img-fluid detail-img d-block mx-auto" src="{{ dog.image.url }}" alt="No image for {{ dog.name }}">
                </div>
                <div class="card-body mb-0">
                    <table class="m-0 p-0" style="width:100%">
                        <tr class="table-row">
                            <td>
                                <h3 class="text-xl my-0 title text-dark">Breed:</h3>
                            </td>
                            <td>
                                <h3 class="text-xl my-0 pl-2 mt-1">{{ dog.breed }}</h3>
                            </td>
                        </tr>
                        <tr class="table-row">
                            <td>
                                <h3 class="text-xl my-0 title text-dark">Age:</h3>
                            </td>
                            <td>
                                <h3 class="text-xl my-0 pl-2 mt-1">
                                    {% if dog.age < 1 %}
                                    Puppy (less than 1 yr)
                                    {% else %}
                                    {{ dog.age }} year{{ dog.age|pluralize:"s" }} old
                                    {% endif %}
                                </h3>
                            </td>
                        </tr>
                        <tr class="table-row">
                            <td>
                                <h3 class="text-xl my-0 title text-dark">Sex:</h3>
                            </td>
                            <td>
                                <h3 class="text-xl my-0 pl-2">{{ dog.get_sex_display }}</h3>
                            </td>
                        </tr>
                        <tr class="table-row">
                            <td>
                                <h3 class="text-xl my-0 title text-dark">Size:</h3>
                            </td>
                            <td>
                                <h3 class="text-xl my-0 pl-2 mt-1">{{ dog.get_size_display }}</h3>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6 mx-auto">
            <div class="container story">
            {% block story %}            
                <h2 class="title mt-0 text-center">
                    {{ dog.name }}'s Story
                </h2>
                <p class="text-lg mb-4">
                    {{ dog.description }}
                </p>
                <div class="text-center">
                    {% if user.is_authenticated %}<a href="{% url 'dogs:update' pk=dog.pk %}"class="ml-3 mt-3 d-inline btn btn-secondary text-dark btn-sm"><i class="fas fa-pencil-alt"></i> Edit</a>
                    <a href="{% url 'dogs:delete' pk=dog.pk %}"class="ml-3 mt-3 d-inline btn btn-danger btn-sm"><i class="fas fa-trash "></i> Delete</a>{% endif %}
                </div>
                {% endblock story %}
            </div>
            
        </div>
    </div>
</div>
</div>
{% endblock page_header %} 

natalies_second_chance_project/dogs/templates/dogs/dog_form.html
{% extends "dogs/dog_list.html" %}
{% load crispy_forms_tags %}
{% load form_tags %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/forms.min.css' %}">
{% endblock  %}


<!-- Checks if the form already has an instance in the database -->
{% block body %}
{% include "includes/detail_navbar.html" %}
<section class='full-page-form'>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-6 col-10 mx-auto">
                <div class="card dog-form">
                    <div class="card-header card-header-success">
                        <h3 class="title">
                            {% if not form.instance.pk %}
                            Create Dog
                            {% else %}
                            Update {{dog.name}}
                            {% endif %}
                        </h3>
                
                    </div>
                    <div class="card-body">
                        <form action="" method="POST" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col">
                                    <p>{{ form.name|as_crispy_field }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <p>{{ form.age|as_crispy_field }}</p>
                                </div>
                                <div class="col-md-6">
                                    <p>{{ form.breed|as_crispy_field }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <p>{{ form.size|as_crispy_field }}</p>
                                </div>
                                <div class="col-md-6">
                                    <p>{{ form.sex|as_crispy_field }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <p>{{ form.description|as_crispy_field }}</p>
                                </div>
                            </div>
                            <div class="row justify-content-center">
                                <div class="col-md-10 text-center">
                                    {% if form.instance.pk %}
                                    {{ form.image.label_tag|safe }}<br>
                                    {{ form.image }}
                                    {% else %}
                                    {{form.image}}
                                    {{form.image|add_label_class:'btn btn-danger'}}
                                    {% endif %}
    
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8 mx-auto text-center">
                                    <output id="imageFileOutput" class="image-file">
                                    </output>
                                    <br>
                                    <img id="preview" class="thumb hidden  mb-2" src="" alt="image preview">
                                </div>
                            </div>
                            <button class="btn form-control btn-success" type="submit">Save {% if dog.name %} {{dog.name}} {% else %}Dog{% endif %}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Enctype needs to be specified to allow population of request.FILES (our image upload)
     For a refresher go to https://docs.djangoproject.com/en/2.1/topics/http/file-uploads/ -->

{% endblock body %}

{% block scripts %}
<script src="{% static 'js/forms.js'%}" type="text/javascript"></script>
{% endblock  %}

natalies_second_chance_project/dogs/templates/dogs/dog_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Dogs
{% endblock  %}
    

{% block stylesheets %}
<!-- Index CSS -->
<link rel="stylesheet" href="{% static 'css/dogs.min.css' %}">
{% endblock  %}


{% block page_header_title %}
Our Dogs
{% endblock  %}

{% block header_buttons %}
{% if user.is_authenticated %}
{% endif %}  
{% endblock header_buttons %}



{% block main %}
<div class="main main-raised">
    <div class="container"> 
        <div class="text-center">
        {% if user.is_authenticated %}
            <a href="{% url 'dogs:create' %}" class="btn btn-info btn-round btn-lg my-4"><i class="fas fa-plus fa-lg"></i> Add Dog</a>
        {% endif %}
        </div>
        <!--Adoptables-->
        <div id="adoptables" class="section pt-4">
            {% include "includes/display_dogs.html" %}
        </div>  
    </div>
</div>
{% endblock  %}
    

natalies_second_chance_project/dogs/templates/pets/dog_create.html
<form action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

natalies_second_chance_project/templates/base.html
<!doctype html> {% load static %}
<html lang="en">

    <head>
        <title>{% block title %}{% endblock %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta http-equiv="Cache-Control" content="no-store">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <!--  Fonts and icons  -->
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons|"
        />
        <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ"
            crossorigin="anonymous">

        <!-- Material Kit CSS -->
        <link href="{% static 'css/material-kit.min.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/base.min.css' %}"> {% block stylesheets %} {% endblock %}
    </head>

    <body>
        {% block body %} 
        {% block navigation %}
        {% include "includes/non_index_navbar.html" %}
        {% endblock navigation %} 
        
        {% block page_header %}
        <div class="page-header header-filter" data-parallax="true">
            <div class="container">
                <!-- Success or error messages for Test User Login-->
                {% if messages %} {% for message in messages %}
                <div {% if message.tags %} class="alert alert-dismissable alert-{{ message.tags }} fade show" {% endif %}>
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %} {% endif %}
                <div class="row">
                    <div class="col-md-8 ml-auto mr-auto">
                        <div class="brand text-center">
                            <h1 class="title" id="title">
                                {% block page_header_title %} {% endblock %}
                            </h1>
                            <!-- Button trigger modal >> modal outside of body -->
                            {% block header_buttons %}
                            <button type="button" class="btn btn-success btn-round" data-toggle="modal" data-target="#donationModal">
                                Donate
                            </button>
                            <a href="#" class="btn d-inline btn-round btn-outline header-btn btn-success">Volunteer</a>
                            <div class="div">

                            </div>

                            {% if user.username == 'test' %}
                            {% else %}
                            <a href="{% url 'test_login' %}" class="btn btn-secondary btn-round">Login as Test User 
                            {% endif %}
                            </a>
                            {% endblock header_buttons %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock page_header %}



        <!-- Donation Modal-->
        <div class="modal fade" id="donationModal" tabindex="-1" role="dialog" aria-labelledby="donationModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header mb-0">
                        <h4 class="title mb-0" id="donationModalLabel">
                            Choose a donation amount
                            <p style="line-height:1.2;" class="mt-1"> Your donation today will help find a home for one of
                                our pups</p>
                            <h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                    </div>
                    {% include "includes/donation_form.html" %}
                </div>
            </div>
        </div>

        {% block main %} {% endblock main %}



        <footer class="footer mt-5 footer-default">
            <div class="container">
                {% comment %}
                <nav class="float-left">
                    <small class="d-inline">
                        Icons made by
                        <a href="http://www.freepik.com" title="Freepik">Freepik</a> from
                        <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by
                        <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC
                            3.0 BY</a>
                    </small>
                </nav> {% endcomment %}
                <div class="copyright">
                    &copy;
                    <script>
                        document.write(new Date().getFullYear())
                    </script>, Donated and made with
                    <i class="material-icons">favorite</i> by
                    <a href="http://www.abepena.com" target="blank">Abe Pena</a>
                </div>
            </div>
        </footer>




        {% endblock body %}
        <!--   Core JS Files   -->
        <script src="{% static 'js/core/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/plugins/moment.min.js' %}"></script>
        <!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker -->
        <script src="{% static 'js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
        <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
        <script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
        <!--  Google Maps Plugin  -->
        <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
        <!-- Place this tag in your head or just before your close body tag. -->
        <!-- <script async defer src="https://buttons.github.io/buttons.js' %}"></script> -->

        <!-- Control Center for Material Kit: parallax effects, scripts for the example pages etc -->
        <script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/index.js' %}" type="text/javascript"></script>
        <!-- Donation Modal JS on donate  button click -->
        <script src="{% static 'js/donation_modal.js' %}"></script> {% if payment %} {% include "includes/payment_modal.html"
        %} {% endif %} {% block scripts %} {% endblock %}
    </body>

</html>

natalies_second_chance_project/templates/events.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Home
{% endblock  %}
  

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/events.min.css' %}">
{% endblock  %}
    

{% block navigation %}
{% include "includes/non_index_navbar.html" %}
{% endblock  %}
    

{% block page_header_title %}
    Events
{% endblock  %}
    
{% block main %}
<div class="main main-raised">          
    <div id="upcoming-events" class="section pt-2">
        <h2 class="title text-center">Upcoming Events</h2>
        <div class="row">
            <div class="col-6">
                
            </div>
        </div>
    </div>
    <div id="past-events" class="section pt-0">
        <h2 class="title text-center">Past Events</h2>
        <div class="row">
            <div class="col-6">
                
            </div>
        </div>
    </div>
</div>
{% endblock  %}
    

natalies_second_chance_project/templates/includes/detail_navbar.html
<!-- Detail Navbar is not transparent to contrast with background-->
<nav class="navbar fixed-top navbar-expand-lg text-dark">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="{% url 'home'%}">
                    Natalie's Second Chance
                </a>
    
                <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon bg-dark"></span>
                    <span class="navbar-toggler-icon bg-dark"></span>
                    <span class="navbar-toggler-icon bg-dark"></span>
                </button>
            </div>
    
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link main-nav-link">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'dogs:list' %}" class="nav-link main-nav-link" rel="tooltip" data-placement="bottom" data-original-title="Adopt a new friend">
                            <i class="fas fa-paw fa-lg"></i> Adoption
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'events' %}" class="nav-link main-nav-link" rel="tooltip" data-placement="bottom" data-original-title="Upcoming Events">
                            <i class="fas fa-bullhorn fa-lg"></i> Events
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'contact' %}" class="nav-link main-nav-link" rel="tooltip" data-placement="bottom" data-original-title="Contact us">
                            <i class="fas fa-tty fa-lg"></i> Contact
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link main-nav-link" rel="tooltip" data-placement="bottom" data-original-title="Help a dog out yourself">
                                <i class="fas fa-hand-holding-heart fa-lg"></i> Donate / Volunteer
                        </a>
                    </li>
                    <li class="nav-item">         
                        <a class="nav-link" rel="tooltip" title="" data-placement="bottom" href="https://www.facebook.com/NataliesSecondChance/"
                            target="_blank" data-original-title="Reach out on Facebook">
                            <i class="fab fa-facebook fa-lg"></i>
                            <div class="ripple-container"></div>
                        </a>
                        </a>
                    </li>
                    {% block nav-items %}
                    {% endblock  %}
                </ul>
            </div>
        </div>
</nav>

natalies_second_chance_project/templates/includes/display_dogs.html
<div class="row justify-content-around">
    {% for dog in dogs %}
    <div class="col-lg-4 col-md-6">
        <div class="card">
            <div class="card-header adopt-header">
                <h3 class="d-inline title">{{ dog.name.capitalize }}</h3>
                {% if user.is_authenticated %}
                <div class="d-inline float-right">
                    <a href="{% url 'dogs:update' pk=dog.pk %}" class="btn btn-secondary text-dark btn-sm">Edit</a>
                </div>
                {%endif %}
            </div>
            <img class="card-img-top img-fluid dog-list-image" src="{{ dog.image.url }}">
            <div class="card-body" style="min-height: 150px">
                <div class="card-title">{{ dog.breed }}: {{ dog.age|default:"Puppy" }} {%if dog.age %}year{{dog.age|pluralize:"s"}} old {% endif %}</div>
                <div class="card-subtitle">{{ dog.description|truncatewords:"20" }}</div>
                <div class="d-inline float-right">
                    <a href="{% url 'dogs:detail' dog.pk %}" class="btn-sm btn-success">More info</a>
                    {% if user.is_authenticated %}
                    <a href="{% url 'dogs:delete' pk=dog.pk %}" class="btn btn-danger btn-sm">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>